apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: partner-catalog
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: partner-catalog
    app.kubernetes.io/part-of: partner-catalog
  name: partner-catalog
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: partner-catalog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: partner-catalog
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/fduthill-tenant/partner-catalog/partner-catalog@sha256:3f0be4b0aed06da1e61e82a746bd4f9b4cb887f68ff862ac2e12f2ac3bcbf7bd
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
